[project]
name = "vietmedkg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.3",
    "py2neo>=2021.2.4",
    "tqdm>=4.67.1",
]
